# Generated by Django 5.2.2 on 2025-06-17 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_description',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='dep_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='home.departments'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_image',
            field=models.ImageField(upload_to='doctors/'),
        ),
    ]
